{{- if eq .Values.mysqlAnalytics.enabled true }}
{{- if eq .Values.mysqlAnalytics.external false }}
apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ .Values.mysqlAnalytics.name }}
  namespace: {{ .Values.global.namespace | quote }} 
spec:
  replicas: 1
  selector:
    matchLabels:
       app: {{ .Values.mysqlAnalytics.name }}
  strategy: 
    type: Recreate
  template:
    metadata:
      labels:
        app: {{ .Values.mysqlAnalytics.name }}
    spec:
      {{- if eq .Values.global.nodeAffinity.enabled true }}
      affinity:
        nodeAffinity:
          requiredDuringSchedulingIgnoredDuringExecution:
            nodeSelectorTerms:
            - matchExpressions:
              - key: agentpool
                operator: In
                values: 
                - {{ .Values.global.nodeAffinity.name }}
      {{- end }}
      containers:
      - image: {{ .Values.mysqlAnalytics.imageName }}:{{ .Values.mysqlAnalytics.buildTag }}
        name: {{ .Values.mysqlAnalytics.name }}
        args:
        - "--ignore-db-dir=lost+found"        
        env:
        - name: MYSQL_DATABASE
          value: {{ .Values.mysqlAnalytics.dbName }}
        - name: MYSQL_ROOT_PASSWORD
          valueFrom:
            secretKeyRef:
              name: apim-password
              key: dbmysqlroot
        - name: MYSQL_USER
          value: {{ .Values.mysqlAnalytics.adminUser }}
        - name: MYSQL_PASSWORD
          valueFrom:
            secretKeyRef:
              name: apim-password
              key: dbmysqlanalytics
        imagePullPolicy: {{ .Values.global.pullPolicy }} 
        ports:
        - containerPort: {{ .Values.mysqlAnalytics.port }}
          protocol: TCP
          name: {{ .Values.mysqlAnalytics.name }}
        volumeMounts:
        - name: mysql-persistent-storage
          mountPath: /var/lib/mysql
      volumes:
      - name: mysql-persistent-storage
        persistentVolumeClaim:
          claimName: mysql-analytics-pvc
      dnsPolicy: ClusterFirst
      restartPolicy: Always
      schedulerName: default-scheduler
      terminationGracePeriodSeconds: 30
{{- end }}
{{- end }}
